server:
  port: 8080
spring:
  mail:
    host: smtp.163.com
    username: username
    password: pwd
    #    port: 465
  redis:
    host: host
    password: pwd
  cache:
    redis:
      time-to-live: 1800000
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxxx:3306/database?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: "xxx"
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://xxxx:3306/database?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: "xxx"
    masterslave:
      #从库负载均衡策略
      load-balance-algorithm-type: round_robin  #轮询
      name: dataSource
      #主库数据源名字
      master-data-source-name: master
      #从库数据源名字
      slave-data-source-names: slave
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml


# 图片存放位置
reggie:
  path: "dir"

MyMail:
  templateCode: "【瑞吉外卖】 您正在进行登录操作，这是您的验证码: {code}，五分钟之内有效。（验证码请勿泄露）"
