server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: *
#      password: *
#  mail:
#    host: *
#    username: *
#    password: *
#    port: 465
#  redis:
#    host: redis.host
#    password: redis.password

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# 图片存放位置
reggie:
  path: "D:/temp/pic/"

MyMail:
  templateCode: "【瑞吉外卖】 您正在进行登录操作，这是您的验证码: {code}，五分钟之内有效。（验证码请勿泄露）"
